POST  http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "nam335",
    "password": "nam"
}

###
POST  http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "nam333",
    "password": "nam"
}

### 
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTk5YzQyZWFmYWE5OTg4NjU1OTYzZjMiLCJpYXQiOjE2Mzc1NTU1MTN9.c3xZyHWEjgED2hqBXjp3fJ6e4u6tPArJS-w-dqsJxw0

{
    "ServiceName": "Undercut43",
    "ServicePrice": "100000"
}